services:
  app:
    platform: linux/amd64
    image: bref/php-82-fpm-dev:2
    ports:
      - "8080:8000"
    volumes:
      - .:/var/task
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
      APP_ENV: dev
      APP_DEBUG: 1
